spring.application.name=api

# Conexi\u00f3n a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/TU_BASE_DE_DATOS_AQUI
spring.datasource.username=TU_USUARIO_AQUI
spring.datasource.password=TU_PASSWORD_AQUI

# Configuraciones flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Configuracion de Puerto
server.port=8081

# Configuraci\u00f3n JWT (Llave de 256 bits generada aleatoriamente en Base64)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiraci\u00f3n del token: 1 d\u00eda en milisegundos (86400000)
jwt.expiration=86400000

# Muestra qu\u00e9 endpoint se est\u00e1 llamando
logging.level.org.springframework.web=DEBUG

# Muestra detalles extra como los par\u00e1metros que te env\u00edan
spring.mvc.log-request-details=true