ALTER TABLE contrato
    ADD COLUMN IF NOT EXISTS created_by UUID,
    ADD COLUMN IF NOT EXISTS created_date TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS last_modified_by UUID,
    ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP,
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE contrato
    DROP COLUMN IF EXISTS creado_en;
